CAR_NGO = {
"ISLAMIC RELIEF WORLDWIDE": ['education', 'healthcare', 'water'],
"INTERNATIONAL RESCUE COMMITTEE, U.K": ['homelessness', 'electricity'],
"INTERNATIONAL MEDICAL CORPS (UK)": ['healthcare'],
"EDUCATION DEVELOPMENT TRUST": ['education'],
"WORLD VISION UK": ['homelessness', 'electricity'],
"CATHOLIC AGENCY FOR OVERSEAS DEVELOPMENT": ['poverty'],
"CONCERN WORLDWIDE (UK)": ['hunger', 'water'],
"PENNY APPEAL": ['water', 'hunger', 'healthcare'],
"SISTERS OF CHARITY OF ST JEANNE ANTIDE CIO": ['homeless', 'education'],
"WAR CHILD": ['orphans'],
"ONE NATION": ['orphans'],
"CONCILIATION RESOURCES": [''],
"A C O R D": ['electricity', 'homelessness', 'water', 'hunger'],
"THE BORN FREE FOUNDATION": ['poaching', 'wildlife'],
"Inspiration Incubator": ['community ', 'society'],
"Everlasting Foundation": ['hunger', 'clothes', 'education'],
"Conserve Global": ['animal'],
"Center fior civilians in conflict(UK)": ['education'],
"Muslim futures": ['education', 'minority'],
"Uptime Catalyst facility": ['water'],
"International Tanaba(ITANABA)": ['poverty', 'animal'],
"The Arcanum foundation": ['youth clubs', 'animal', 'veterans'],
"Kariba Health Organizatiion": ['healthcare'],
"African Rights Action": ['inclusion', 'refugees'],
"International Welfare Allience(IWARELIEF)": ['healthcare', 'hunger', 'clothing', 'homelessness', 'electricity'],
"KD Foundation": ['climate',  'hunger' , 'clothing', 'education', 'healthcare'],
"Smart": ['hunger'],
"Thirdway Trust": ['education'],
"AFDP Globsl Foundation": ['sports'],
"International Shadow Piece Force": ['war', 'refugees'],
"International Wildlife Bond": ['animal'],
"Central African Organization": ['homelessness', 'electricity']
}
