CAR_NGO = {
"ISLAMIC RELIEF WORLDWIDE": ['education', 'healthcare', 'water'],
"INTERNATIONAL RESCUE COMMITTEE, U.K": ['homelessness', 'electricity'],
"INTERNATIONAL MEDICAL CORPS (UK)": ['healthcare'],
"EDUCATION DEVELOPMENT TRUST": ['education', 'literacy'],
"WORLD VISION UK": ['homelessness', 'electricity'],
"CATHOLIC AGENCY FOR OVERSEAS DEVELOPMENT": ['poverty'],
"CONCERN WORLDWIDE (UK)": ['hunger', 'water'],
"PENNY APPEAL": ['water', 'hunger', 'healthcare'],
"SISTERS OF CHARITY OF ST JEANNE ANTIDE CIO": ['homeless', 'education', 'literacy'],
"WAR CHILD": ['orphans'],
"ONE NATION": ['orphans'],
"CONCILIATION RESOURCES": [''],
"A C O R D": ['electricity', 'homelessness', 'water', 'hunger'],
"THE BORN FREE FOUNDATION": ['poaching', 'wildlife'],
"Inspiration Incubator": ['community ', 'society'],
"Everlasting Foundation": ['hunger', 'clothes', 'education'],
"Conserve Global": ['animal'],
"Center fior civilians in conflict(UK)": ['education'],
"Muslim futures": ['education', 'literacy', 'minority'],
"Uptime Catalyst facility": ['water'],
"International Tanaba(ITANABA)": ['poverty', 'animal'],
"The Arcanum foundation": ['youth clubs', 'animal', 'veterans'],
"Kariba Health Organizatiion": ['healthcare'],
"African Rights Action": ['inclusion', 'refugees'],
"International Welfare Allience(IWARELIEF)": ['healthcare', 'hunger', 'clothing', 'homelessness', 'electricity'],
"KD Foundation": ['climate',  'hunger' , 'clothing', 'education', 'healthcare'],
"Smart": ['hunger'],
"Thirdway Trust": ['education', 'literacy'],
"AFDP Globsl Foundation": ['sports'],
"International Shadow Piece Force": ['war', 'refugees'],
"International Wildlife Bond": ['animal'],
"Central African Organization": ['homelessness', 'electricity']
}

global_NGO = {
            'WWF': ['pollution'], 
            'SISTERS of CHARITY of ST JEANNE ANTIDE CIO': ['homelessness', 'religion'],
            'CHURCH MISSION SOCIETY': ['religion', 'cultural divides'],
            'WORLD LAND TRUST': ['pollution'],
            'YOUTH BUSINESS INTERNATIONAL': ['business'], 
            'OPERATIONAL SMILE UNITED KINGDOM': ['healthcare'],
            'FAMILY for EVERY CHILD': ['education', 'literacy'],
            'GLOBAL CANOPY': ['pollution'],
            'TEACH A MAN TO FISH': ['business'],
            'THE GLOBAL WARMING POLICY FOUNDATION': ['pollution'],
            'THE SLOTH CONSERVATION FOUNDATION': ['education', 'literacy', 'shelter', 'pollution'],
            'GOOD NEIGHBOURS UK': ['human rights'],
            'THE INTERNATIONAL CML FOUNDATION': ['diseases'],
            'WATER SURVIVAL BOX LTD': ['water'],
            'MISSIONARY SISTERS OF THE SACRED HEART': ['education', 'literacty', 'healthcare', 'poverty'],
            'SANTA MARIA EDUCATION FUND': ['education','literacy', 'poverty'],
            'NEOTOPICAL BIRD CLUB': ['wildlife'],
            'ARCAID': ['natural disasters'],
            'OXFAM': ['famine'], 
            'CONCERN WORLDWIDE': ['healthcare', 'education', 'literacy', 'climate'],
            'WORLD RELIEF': ['poverty', 'natural disasters,'],
            'CARE INTERNATIONAL': ['poverty', 'healthcare', 'water']
}