CAR_NGO = {
"ISLAMIC RELIEF WORLDWIDE": ['education', 'healthcare', 'water'],
"INTERNATIONAL RESCUE COMMITTEE, U.K": ['homelessness', 'electricity', 'water'],
"INTERNATIONAL MEDICAL CORPS (UK)": ['healthcare'],
"EDUCATION DEVELOPMENT TRUST": ['education'],
"WORLD VISION UK": ['homelessness', 'electricity', 'water'],
"CATHOLIC AGENCY FOR OVERSEAS DEVELOPMENT": ['poverty'],
"CONCERN WORLDWIDE (UK)": ['hunger', 'water'],
"PENNY APPEAL": ['water', 'hunger', 'healthcare'],
"SISTERS OF CHARITY OF ST JEANNE ANTIDE CIO": ['homeless', 'education', 'water'],
"WAR CHILD": ['orphans'],
"ONE NATION": ['orphans'],
"CONCILIATION RESOURCES": ['hunger'],
"A C O R D": ['electricity', 'homelessness', 'water', 'hunger'],
"THE BORN FREE FOUNDATION": ['poaching', 'wildlife'],
"Inspiration Incubator": ['community ', 'society'],
"Everlasting Foundation": ['hunger', 'clothes', 'education'],
"Conserve Global": ['animal'],
"Center fior civilians in conflict(UK)": ['education'],
"Muslim futures": ['education', 'minority'],
"Uptime Catalyst facility": ['water'],
"International Tanaba(ITANABA)": ['poverty', 'animal'],
"The Arcanum foundation": ['youth clubs', 'animal', 'veterans'],
"Kariba Health Organizatiion": ['healthcare'],
"African Rights Action": ['inclusion', 'refugees'],
"International Welfare Allience(IWARELIEF)": ['healthcare', 'hunger', 'clothing', 'homelessness', 'electricity'],
"KD Foundation": ['climate',  'hunger' , 'clothing', 'education', 'healthcare'],
"Smart": ['hunger'],
"Thirdway Trust": ['education'],
"AFDP Globsl Foundation": ['sports'],
"International Shadow Piece Force": ['war', 'refugees'],
"International Wildlife Bond": ['animal'],
"Central African Organization": ['homelessness', 'electricity']
}

global_NGO = {
"INTERNATIONAL RESCUE COMMITTEE, U.K": ['homelessness', 'electricity', 'water'],
"INTERNATIONAL MEDICAL CORPS (UK)": ['healthcare', 'obesity', 'mortality'],
"WORLD VISION UK": ['homelessness', 'electricity', 'water'],
"International Tanaba(ITANABA)": ['poverty', 'animal'],
'WWF': ['pollution'], 
'SISTERS of CHARITY of ST JEANNE ANTIDE CIO': ['homeless', 'religion'],
'CHURCH MISSION SOCIETY': ['religion', 'cultural divides'],
'WORLD LAND TRUST': ['pollution'],
'YOUTH BUSINESS INTERNATIONAL': ['business'], # economy
'OPERATIONAL SMILE UNITED KINGDOM': ['healthcare', 'obesity', 'mortality'],
'FAMILY for EVERY CHILD': ['education'],
'GLOBAL CANOPY': ['pollution'],
'TEACH A MAN TO FISH': ['business'],
'THE GLOBAL WARMING POLICY FOUNDATION': ['pollution'],
'THE SLOTH CONSERVATION FOUNDATION': ['education', 'shelter', 'pollution'],
'GOOD NEIGHBOURS UK': ['human rights'],
'THE INTERNATIONAL CML FOUNDATION': ['diseases'],
'WATER SURVIVAL BOX LTD': ['water'],
'MISSIONARY SISTERS OF THE SACRED HEART': ['education', 'healthcare', 'poverty', 'obesity', 'mortality'],
'SANTA MARIA EDUCATION FUND': ['education', 'poverty'],
'NEOTOPICAL BIRD CLUB': ['wildlife'],
'ARCAID': ['natural disasters']
}