global_NGO = {
"INTERNATIONAL RESCUE COMMITTEE, U.K": ['homelessness', 'electricity', 'water'],
"INTERNATIONAL MEDICAL CORPS (UK)": ['healthcare', 'obesity', 'mortality'],
"WORLD VISION UK": ['homelessness', 'electricity', 'water'],
"International Tanaba(ITANABA)": ['poverty', 'animal'],
'WWF': ['pollution'], 
'SISTERS of CHARITY of ST JEANNE ANTIDE CIO': ['homeless', 'religion'],
'CHURCH MISSION SOCIETY': ['religion', 'cultural divides'],
'WORLD LAND TRUST': ['pollution'],
'YOUTH BUSINESS INTERNATIONAL': ['business'], # economy
'OPERATIONAL SMILE UNITED KINGDOM': ['healthcare', 'obesity', 'mortality'],
'FAMILY for EVERY CHILD': ['education'],
'GLOBAL CANOPY': ['pollution'],
'TEACH A MAN TO FISH': ['business'],
'THE GLOBAL WARMING POLICY FOUNDATION': ['pollution'],
'THE SLOTH CONSERVATION FOUNDATION': ['education', 'shelter', 'pollution'],
'GOOD NEIGHBOURS UK': ['human rights'],
'THE INTERNATIONAL CML FOUNDATION': ['diseases'],
'WATER SURVIVAL BOX LTD': ['water'],
'MISSIONARY SISTERS OF THE SACRED HEART': ['education', 'healthcare', 'poverty', 'obesity', 'mortality'],
'SANTA MARIA EDUCATION FUND': ['education', 'poverty'],
'NEOTOPICAL BIRD CLUB': ['wildlife'],
'ARCAID': ['natural disasters'],
'OXFAM': ['famine'], 
'CONCERN WORLDWIDE': ['healthcare', 'education', 'literacy', 'climate'],
'WORLD RELIEF': ['poverty', 'natural disasters,'],
'CARE INTERNATIONAL': ['poverty', 'healthcare', 'water'],
'DOCTORS WITHOUT BORDERS': ['healthcare', 'obesity', 'mortality'],
'PROJECT HOPE': ['diseases', 'healthcare', 'natural disasters', 'obesity', 'mortality'],
"GREEN PEACE": ['pollution']
}